import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// Modify the title, description, and icons as needed
export const metadata: Metadata = {
  title: "Next13 app",
  description: "Generated by Jeffrey",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          {/* Navbar globally */}
          <nav>
            <Link href="/"> Home </Link>
            <Link href="/notes"> Notes </Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
